### ISSUE TITLE
Document prerequisites

### ISSUE THREAD

**Issue by juckele** [Jire/Strukt#1]
This looks really awesome, I'm really excited to give this a try sometime. What are the prerequisites for use of this library? Which JVM languages can this be used with? Kotlin? Java? Is it possible to get syntax examples for Java if it can be used with Java?

**Comment by Jire** [comment]
Kotlin is supported completely, but I believe more work is needed to easily use Strukt in other languages.

I'll get back to you when and if I update the library with Java in mind.

**Comment by Jire** [comment]
@juckele Finished support for other JVM languages.

Here's a basic example in Java...

Declaring a Strukt:
```java
import org.jire.strukt.member.Members;

public final Point extends Strukt {
    public final IntMember x = Members.intMember(3);
    public final IntMember y = Members.intMember(5);

    public static final Point POINT = new Point();
}
```

Allocation (assuming `Point.POINT` is statically imported):
```java
long threeFive = POINT.allocate();
```

Setting/getting:
```java
POINT.x.get(); // 3
POINT.y.set(1337);
```

Also all `toString`s are implemented on the members now, so you can print directly:
```java
System.out.println(POINT.x + ", " + POINT.y); // prints "3, 1337"
```

Deallocation (assuming `Deallocate.deallocate` is statically imported):
```java
deallocate(threeFive);
```

**Comment by juckele** [comment]
Wow, this is looking really nice. I can't wait to give this a try 👍
