### ISSUE TITLE
The pointer isn't threadsafe

### ISSUE THREAD

**Issue by Eladkay** [Jire/Strukt#2]
If one thread expects the pointer to remain set, while another thread sets it to a different value, undefined behavior may occur. The pointer needs to be thread-local.

**Comment by Jire** [comment]
You're right, and it's by intention because thread-localizing the pointer degrades performance slightly. The bigger issue is it's still not safe unless everything is thread-localized. Need to come up with some solution for this.

**Comment by Jire** [comment]
2.0.0 no longer uses pointer variable
